apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-admin-creds
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: prod/jenkins/admin
        property: username
    - secretKey: jenkins-admin-password
      remoteRef:
        key: prod/jenkins/admin
        property: password