apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token-es
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: github-token
    creationPolicy: Owner
    template:
      metadata:
        labels:
          jenkins.io/credentials-type: usernamePassword
  data:
    - secretKey: username
      remoteRef:
        key: prod/jenkins/github
        property: username
    - secretKey: password
      remoteRef:
        key: prod/jenkins/github
        property: password