image:
  # Замініть на свій AWS Account ID
  repository: "995370108987.dkr.ecr.eu-central-1.amazonaws.com/demo-ecr"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "django_user"
  POSTGRES_DB: "django_db"

secrets:
  # Значення передається ззовні під час розгортання
  POSTGRES_PASSWORD: ""