image:
  # Замініть на свій AWS Account ID
  repository: "995370108987.dkr.ecr.eu-central-1.amazonaws.com/demo-ecr"
  tag: "8-b4382554"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
